name: Test DAGs
on:
  push:
    branches:
      - my_repo
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip check
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 --ignore E501 dags --benchmark -v
    - name: Confirm Black code compliance
      run: |
        pip install pytest-black
        pytest dags --black -v
    - name: Test with Pytest
      run: |
        pip install pytest
        cd tests || exit
        pytest test.py -v
    - name: Test with Unittest
      run: |
        cd tests || exit
        pytest test2.py -v
    - name: test project
      if: github.event_name == 'push'
      run: |
        echo "New line only when merge"
        echo "${{ github.ref }}"
    - uses: repo-sync/pull-request@v2
      name: pull request to Develop
      if: github.event_name == 'push' && github.ref == 'refs/heads/my_repo'
      with:
        destination_branch: "develop"
        pr_title: "Pulling ${{ github.ref }} into develop"
        pr_body: " Automatic Action"
        pr_reviewer: "Estebrock09"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}